-- ============================================================================
-- File: 02_category_revenue_query.sql
-- Video chapter: Building the report visually
-- Database: retail_ops_dev
-- Purpose:
--   Aggregate completed-order revenue by customer country, product category,
--   and sales channel for July 2026.
--
-- Note:
--   This is the reference SQL for the Query Builder demonstration. The exact
--   formatting or alias placement generated by the visual builder may differ,
--   but the resulting query should preserve this logic.
-- ============================================================================

SELECT
    c.country_code,
    cat.category_name,
    o.sales_channel,
    SUM(oi.quantity)::BIGINT AS units_sold,
    ROUND(
        SUM(
            oi.quantity
            * oi.unit_price
            * (1 - oi.discount_percent / 100.0)
        ),
        2
    ) AS net_revenue
FROM sales.customers AS c
INNER JOIN sales.orders AS o
    ON o.customer_id = c.customer_id
INNER JOIN sales.order_items AS oi
    ON oi.order_id = o.order_id
INNER JOIN sales.products AS p
    ON p.product_id = oi.product_id
INNER JOIN sales.categories AS cat
    ON cat.category_id = p.category_id
WHERE o.status = 'completed'
  AND o.ordered_at >= TIMESTAMPTZ '2026-07-01 00:00:00+05'
  AND o.ordered_at < TIMESTAMPTZ '2026-08-01 00:00:00+05'
GROUP BY
    c.country_code,
    cat.category_name,
    o.sales_channel
ORDER BY net_revenue DESC;
